---
- name: Download the source code for a release of Nagios Core and extract it
  unarchive: src=https://assets.nagios.com/downloads/nagioscore/releases/nagios-{{ nagios_version }}.tar.gz dest={{ ansible_env.PWD }} copy=no
  tags:
    - dwld_nagios

- name: Configure Nagios
  command: ./configure --with-nagios-group={{ user }} --with-command-group={{ group }}
  args:
    chdir: "{{ ansible_env.PWD }}/nagios-{{ nagios_version }}"
  tags:
    - cfg_nagios

- name: Compile Nagios
  command: "{{ item }}"
  args:
    chdir: "{{ ansible_env.PWD }}/nagios-{{ nagios_version }}"
  with_items:
    - make clean
    - make all
    - make install
    - make install-commandmode
    - make install-init
    - make install-config
  tags:
   - cfg_nagios

- name:  Install Nagios and init scripts
  command: /usr/bin/install -c -m 644 sample-config/httpd.conf /etc/apache2/sites-available/nagios.conf
  args:
    chdir: "{{ ansible_env.PWD }}/nagios-{{ nagios_version }}"
  tags:
    - nagios_init

- name:  Add the web server user to the group
  command: usermod -G {{ group }} www-data
  args:
    chdir: "{{ ansible_env.PWD }}/nagios-{{ nagios_version }}"
  tags:
    - nagios_init