---
- name: Create Nagios User and Group
  shell: useradd nagios; groupadd nagcmd; usermod -a -G nagcmd nagios

- name: Update repo cache and install build dependencies
  apt: name="{{item}}" state=present update_cache=yes
  with_items:
  - build-essential
  - libgd2-xpm-dev
  - openssl
  - libssl-dev
  - xinetd
  - apache2-utils
  - unzip